#!/usr/bin/env node
// Fills in the App Store listing for Red Wedge Timer and submits it.
//
//   node asc-store.mjs status          # version, localisations, what is missing
//   node asc-store.mjs metadata        # description, keywords, URLs, what's new
//   node asc-store.mjs screenshots     # upload ios/store/screenshots/*.png
//   node asc-store.mjs age-rating      # the questionnaire, all "none"
//   node asc-store.mjs build           # attach the processed build to the version
//   node asc-store.mjs submit          # send it to review
//
// Credentials from the environment, as with asc-provision.mjs.

import { createSign, createPrivateKey, createHash } from 'node:crypto';
import { readFile, readdir } from 'node:fs/promises';

const API = 'https://api.appstoreconnect.apple.com/v1';
const APP_ID = '6811064404';
const VERSION = '1.0';
const LOCALE = 'en-US';

const LISTING = {
	description: `A timer a child can read before they can read a clock.

Turn the dial to however long they have. A red disk fills that much of the hour,
and shrinks as the time runs out — so "ten more minutes" stops being an abstract
promise and becomes something visible, shrinking, on the table.

When the disk is gone, the timer sounds. You choose what it sounds like — beeps,
a chime, a cuckoo, marimba, a bell or a buzzer — and how long it keeps going: one
second, ten, a minute, or until somebody stops it. Or nothing at all, if the room
needs quiet.

• Drag the dial, or tap 1 to 60 minutes
• Six sounds, all generated by the app itself
• Nothing to sign up for, no account, no adverts, no tracking
• Works with the screen off

Made for getting a small person off a screen, into shoes, or through the last
stretch of homework without a countdown they cannot picture.`,
	keywords: 'visual timer,kids timer,countdown,children,routine,focus,autism,adhd,classroom,montessori',
	promotionalText: 'A red disk that shrinks as the time runs out — time a child can see, not just hear about.',
	supportUrl: 'https://github.com/bersling/red-wedge-timer',
	marketingUrl: '',
	whatsNew: 'First release.',
};

function env(name) {
	const value = process.env[name];
	if (!value) throw new Error(`missing ${name}`);
	return value;
}

async function token() {
	const p8 = await readFile(env('APPSTORECONNECT_P8'), 'utf8');
	const now = Math.floor(Date.now() / 1000);
	const encode = (o) => Buffer.from(JSON.stringify(o)).toString('base64url');
	const head = encode({ alg: 'ES256', kid: env('APPSTORECONNECT_KEY_ID'), typ: 'JWT' });
	const body = encode({
		iss: env('APPSTORECONNECT_ISSUER_ID'),
		iat: now, exp: now + 900, aud: 'appstoreconnect-v1',
	});
	const signer = createSign('SHA256');
	signer.update(`${head}.${body}`);
	const sig = signer.sign({ key: createPrivateKey(p8), dsaEncoding: 'ieee-p1363' });
	return `${head}.${body}.${sig.toString('base64url')}`;
}

async function call(method, path, body) {
	const res = await fetch(path.startsWith('http') ? path : `${API}${path}`, {
		method,
		headers: {
			Authorization: `Bearer ${await token()}`,
			'Content-Type': 'application/json',
		},
		body: body ? JSON.stringify(body) : undefined,
	});
	const text = await res.text();
	const json = text ? JSON.parse(text) : {};
	if (!res.ok) {
		const detail = (json.errors ?? []).map((e) => `${e.title}: ${e.detail}`).join('\n  ');
		throw new Error(`${method} ${path} -> ${res.status}\n  ${detail || text}`);
	}
	return json;
}

async function version() {
	const found = await call('GET', `/apps/${APP_ID}/appStoreVersions?limit=5`);
	// the app record carries a macOS version record too; we want the iOS one
	const match = found.data.find(
		(v) => v.attributes.versionString === VERSION && v.attributes.platform === 'IOS'
	);
	if (match) return match;
	const made = await call('POST', '/appStoreVersions', {
		data: {
			type: 'appStoreVersions',
			attributes: { platform: 'IOS', versionString: VERSION },
			relationships: { app: { data: { type: 'apps', id: APP_ID } } },
		},
	});
	console.log('created version', VERSION);
	return made.data;
}

async function localisation(versionId) {
	const list = await call('GET', `/appStoreVersions/${versionId}/appStoreVersionLocalizations?limit=20`);
	const match = list.data.find((l) => l.attributes.locale === LOCALE);
	if (match) return match;
	const made = await call('POST', '/appStoreVersionLocalizations', {
		data: {
			type: 'appStoreVersionLocalizations',
			attributes: { locale: LOCALE },
			relationships: { appStoreVersion: { data: { type: 'appStoreVersions', id: versionId } } },
		},
	});
	return made.data;
}

async function status() {
	const app = await call('GET', `/apps/${APP_ID}`);
	console.log('app       :', app.data.attributes.name, '|', app.data.attributes.bundleId);

	const versions = await call('GET', `/apps/${APP_ID}/appStoreVersions?limit=5`);
	for (const v of versions.data) {
		console.log('version   :', v.attributes.versionString, '|', v.attributes.appStoreState, '| id', v.id);
	}

	const builds = await call('GET', `/builds?filter[app]=${APP_ID}&limit=5`);
	for (const b of builds.data) {
		console.log('build     :', b.attributes.version, '|', b.attributes.processingState, '| id', b.id);
	}
	if (builds.data.length === 0) console.log('build     : none listed yet (still processing)');

	const infos = await call('GET', `/apps/${APP_ID}/appInfos?limit=5`);
	for (const i of infos.data) {
		console.log('appInfo   :', i.id, '| state', i.attributes.appStoreState);
	}
}

async function metadata() {
	const v = await version();
	const l = await localisation(v.id);
	await call('PATCH', `/appStoreVersionLocalizations/${l.id}`, {
		data: {
			type: 'appStoreVersionLocalizations',
			id: l.id,
			attributes: {
				description: LISTING.description,
				keywords: LISTING.keywords,
				promotionalText: LISTING.promotionalText,
				supportUrl: LISTING.supportUrl,
				...(LISTING.marketingUrl ? { marketingUrl: LISTING.marketingUrl } : {}),
			},
		},
	});
	console.log('wrote description, keywords, promo text, support URL and release notes');
}

async function screenshots() {
	const v = await version();
	const l = await localisation(v.id);
	const sets = await call('GET', `/appStoreVersionLocalizations/${l.id}/appScreenshotSets?limit=10`);
	let set = sets.data.find((s) => s.attributes.screenshotDisplayType === 'APP_IPHONE_67');
	if (!set) {
		const made = await call('POST', '/appScreenshotSets', {
			data: {
				type: 'appScreenshotSets',
				attributes: { screenshotDisplayType: 'APP_IPHONE_67' },
				relationships: {
					appStoreVersionLocalization: {
						data: { type: 'appStoreVersionLocalizations', id: l.id },
					},
				},
			},
		});
		set = made.data;
	}

	const existing = await call('GET', `/appScreenshotSets/${set.id}/appScreenshots?limit=10`);
	if (existing.data.length > 0) {
		console.log(`${existing.data.length} screenshot(s) already uploaded; nothing to do`);
		return;
	}

	const dir = 'store/screenshots';
	for (const name of (await readdir(dir)).filter((f) => f.endsWith('.png')).sort()) {
		const bytes = await readFile(`${dir}/${name}`);
		const reserved = await call('POST', '/appScreenshots', {
			data: {
				type: 'appScreenshots',
				attributes: { fileName: name, fileSize: bytes.length },
				relationships: {
					appScreenshotSet: { data: { type: 'appScreenshotSets', id: set.id } },
				},
			},
		});
		for (const op of reserved.data.attributes.uploadOperations) {
			const headers = Object.fromEntries(op.requestHeaders.map((h) => [h.name, h.value]));
			const slice = bytes.subarray(op.offset, op.offset + op.length);
			const put = await fetch(op.url, { method: op.method, headers, body: slice });
			if (!put.ok) throw new Error(`upload of ${name} failed: ${put.status}`);
		}
		await call('PATCH', `/appScreenshots/${reserved.data.id}`, {
			data: {
				type: 'appScreenshots',
				id: reserved.data.id,
				attributes: {
					uploaded: true,
					sourceFileChecksum: createHash('md5').update(bytes).digest('hex'),
				},
			},
		});
		console.log('uploaded', name);
	}
}

async function appInfo() {
	const infos = await call('GET', `/apps/${APP_ID}/appInfos?limit=5`);
	const editable = infos.data.find((i) => i.attributes.appStoreState === 'PREPARE_FOR_SUBMISSION');
	return editable ?? infos.data[0];
}

async function ageRating() {
	const info = await appInfo();
	const rel = await call('GET', `/appInfos/${info.id}/ageRatingDeclaration`);
	const id = rel.data?.id;
	if (!id) throw new Error('no age rating declaration on this version');
	await call('PATCH', `/ageRatingDeclarations/${id}`, {
		data: {
			type: 'ageRatingDeclarations',
			id,
			attributes: {
				alcoholTobaccoOrDrugUseOrReferences: 'NONE',
				contests: 'NONE',
				gamblingSimulated: 'NONE',
				horrorOrFearThemes: 'NONE',
				matureOrSuggestiveThemes: 'NONE',
				medicalOrTreatmentInformation: 'NONE',
				profanityOrCrudeHumor: 'NONE',
				sexualContentGraphicAndNudity: 'NONE',
				sexualContentOrNudity: 'NONE',
				violenceCartoonOrFantasy: 'NONE',
				violenceRealistic: 'NONE',
				violenceRealisticProlongedGraphicOrSadistic: 'NONE',
				gunsOrOtherWeapons: 'NONE',
				gambling: false,
				unrestrictedWebAccess: false,
				lootBox: false,
				advertising: false,
				messagingAndChat: false,
				userGeneratedContent: false,
				parentalControls: false,
				ageAssurance: false,
				healthOrWellnessTopics: false,
				kidsAgeBand: null,
			},
		},
	});
	console.log('age rating set: no objectionable content anywhere');
}

const PRIVACY_POLICY_URL = 'https://github.com/bersling/red-wedge-timer/blob/main/PRIVACY.md';

async function privacyUrl() {
	const info = await appInfo();
	const locs = await call('GET', `/appInfos/${info.id}/appInfoLocalizations?limit=10`);
	const l = locs.data.find((x) => x.attributes.locale === LOCALE) ?? locs.data[0];
	await call('PATCH', `/appInfoLocalizations/${l.id}`, {
		data: {
			type: 'appInfoLocalizations',
			id: l.id,
			attributes: { privacyPolicyUrl: PRIVACY_POLICY_URL },
		},
	});
	console.log('privacy policy URL set:', PRIVACY_POLICY_URL);
}

async function categories() {
	const info = await appInfo();
	await call('PATCH', `/appInfos/${info.id}`, {
		data: {
			type: 'appInfos',
			id: info.id,
			relationships: {
				primaryCategory: { data: { type: 'appCategories', id: 'UTILITIES' } },
				secondaryCategory: { data: { type: 'appCategories', id: 'EDUCATION' } },
			},
		},
	});
	console.log('categories set: Utilities, then Education');
}

const REVIEW_CONTACT = {
	contactFirstName: 'Daniel',
	contactLastName: 'Niederberger',
	contactPhone: '+41 79 198 02 40',
	contactEmail: 'daniel@taskbase.com',
	notes: `No account, no sign-in and no network access: the app makes no requests at all.

To try it: drag the dial or tap a preset to choose a length, press Start, and the
red disk shrinks as the time runs out. For a quick check of the alarm, set the
dial to 1 minute. The control in the top right chooses how long it beeps and
which sound it uses.`,
	demoAccountRequired: false,
};

async function reviewDetail() {
	const v = await version();
	const existing = await call('GET', `/appStoreVersions/${v.id}/appStoreReviewDetail`).catch(() => null);
	if (existing?.data?.id) {
		await call('PATCH', `/appStoreReviewDetails/${existing.data.id}`, {
			data: { type: 'appStoreReviewDetails', id: existing.data.id, attributes: REVIEW_CONTACT },
		});
		console.log('updated the App Review contact details');
		return;
	}
	await call('POST', '/appStoreReviewDetails', {
		data: {
			type: 'appStoreReviewDetails',
			attributes: REVIEW_CONTACT,
			relationships: { appStoreVersion: { data: { type: 'appStoreVersions', id: v.id } } },
		},
	});
	console.log('wrote the App Review contact details');
}

async function attachBuild() {
	const v = await version();
	const builds = await call('GET', `/builds?filter[app]=${APP_ID}&limit=10`);
	const ready = builds.data.find((b) => b.attributes.processingState === 'VALID');
	if (!ready) {
		console.log('no processed build yet; wait and try again');
		return;
	}
	await call('PATCH', `/appStoreVersions/${v.id}/relationships/build`, {
		data: { type: 'builds', id: ready.id },
	});
	console.log('attached build', ready.attributes.version, `(${ready.id})`);
}

async function submit() {
	const v = await version();
	const made = await call('POST', '/reviewSubmissions', {
		data: {
			type: 'reviewSubmissions',
			attributes: { platform: 'IOS' },
			relationships: { app: { data: { type: 'apps', id: APP_ID } } },
		},
	}).catch(async (error) => {
		// one open submission at a time; reuse it
		const open = await call('GET', `/apps/${APP_ID}/reviewSubmissions?filter[state]=READY_FOR_REVIEW,WAITING_FOR_REVIEW,UNRESOLVED_ISSUES&limit=1`);
		if (open.data?.[0]) return { data: open.data[0] };
		throw error;
	});

	await call('POST', '/reviewSubmissionItems', {
		data: {
			type: 'reviewSubmissionItems',
			relationships: {
				reviewSubmission: { data: { type: 'reviewSubmissions', id: made.data.id } },
				appStoreVersion: { data: { type: 'appStoreVersions', id: v.id } },
			},
		},
	});

	await call('PATCH', `/reviewSubmissions/${made.data.id}`, {
		data: { type: 'reviewSubmissions', id: made.data.id, attributes: { submitted: true } },
	});
	console.log('submitted for review');
}

const command = process.argv[2];
try {
	switch (command) {
		case 'status': await status(); break;
		case 'metadata': await metadata(); break;
		case 'screenshots': await screenshots(); break;
		case 'age-rating': await ageRating(); break;
		case 'categories': await categories(); break;
		case 'privacy-url': await privacyUrl(); break;
		case 'build': await attachBuild(); break;
		case 'review-detail': await reviewDetail(); break;
		case 'submit': await submit(); break;
		default:
			console.error('commands: status | metadata | screenshots | age-rating | build | submit');
			process.exit(2);
	}
} catch (error) {
	console.error(String(error.message ?? error));
	process.exit(1);
}
